name: Run Instagram Creator Tool

on: [push]

jobs:
  create-account:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install required Python packages
      run: |
        pip install requests

    - name: Run Instagram creator script
      run: |
        echo "1" | python email_reg.py
